name: Node.js CI

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check files
      run: |
        echo "Building and checking files..."
        # This is where your actual build commands would go.
        # Since you have a simple index.html, we'll just check for it.
        ls -l
        if [ -f "index.html" ]; then
          echo "index.html exists. Build check passed!"
          exit 0
        else
          echo "index.html not found. Build check failed."
          exit 1
        fi
